name:           numeric-domains
version:        0.1.0.0
github:         "typedbyte/numeric-domains"
license:        BSD3
author:         "Michael Szvetits"
maintainer:     "typedbyte@qualified.name"
copyright:      "2019 Michael Szvetits"
synopsis:       Numeric Domains
category:       Math
description:    Please see the README on GitHub at <https://github.com/typedbyte/numeric-domains#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

ghc-options: -Wall